# Generated by Django 3.1.2 on 2020-10-20 06:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='selection',
            name='v_down_img',
        ),
        migrations.RemoveField(
            model_name='selection',
            name='v_up_img',
        ),
    ]
